// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34Ur-ufQBbGjc-Vu-qdwcNmpMZaUSJa4',
    appId: '1:823552504826:android:24cdafc65fb55dbc1c2a43',
    messagingSenderId: '823552504826',
    projectId: 'testproject-c0d84',
    databaseURL: 'https://testproject-c0d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testproject-c0d84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQpTHGQXw9ZguMKSQ9WIEbxcPqYrv238',
    appId: '1:823552504826:ios:ec403fa8fa00fb891c2a43',
    messagingSenderId: '823552504826',
    projectId: 'testproject-c0d84',
    databaseURL: 'https://testproject-c0d84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testproject-c0d84.appspot.com',
    iosClientId: '823552504826-s1gkh6pedt1tmeg01g14lqcuatp49lt9.apps.googleusercontent.com',
    iosBundleId: 'com.v24StudentApp.ios',
  );
}
